version: "3.9"
# Para rodar o arquivo, renomeie para "docker-compose.yml" e utilize o comando "docker compose up"
# Para rodar no servidor do cefet, é necessaria a implementação de proxy reverso
services:
  frontend:
    container_name: MicelioDashboard
    image: node:lts-alpine
    working_dir: "/MicelioDashboard"
    command: sh -c "yarn install && yarn start"
    ports:
      - "8080:3000"
    volumes:
      - ./MicelioDashboard:/MicelioDashboard
      - /MicelioDashboard/node_modules
    environment:
      REACT_APP_API_BASE_URL: "/api/" # Para rodar no servidor, pois tem proxy reverso
      NODE_OPTIONS: "--openssl-legacy-provider"
    networks:
      - micelio_network
    restart: always

  backend:
    container_name: MicelioAPI
    image: node:lts-alpine
    working_dir: "/MicelioAPI"
    command: sh -c "yarn install && yarn dev"
    ports:
      - "3002:3002"
    volumes:
      - ./MicelioAPI:/MicelioAPI
    environment: # Dados do banco de dados do backend deverão ser modificados aqui de acordo com o banco
      ENV: development
      HTTP_PORT: "3002"
      JWT_SECRET: ""
      DATABASE_HOST: "172.20.0.1"
      DATABASE_PASSWORD: ""
      DATABASE_USER: ""
      DATABASE_CLIENT: "mysql"
      DATABASE: "micelio"
    networks:
      micelio_network:
        ipv4_address: 172.20.0.10 #IP que tenta conectar ao mysql e tem que estar liberado no usuário do mysql no servidor
    restart: always

networks:
  micelio_network:
    name: micelio_network
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1
