version: "3.9"
# Para rodar o arquivo, renomeie para "docker-compose.yml" e utilize o comando "docker compose up"
services:
  frontend:
    container_name: MicelioDashboard
    image: node:lts-alpine
    working_dir: "/MicelioDashboard"
    command: sh -c "yarn install && yarn start"
    ports: 
      - "8080:3000"
    volumes:
      - ./MicelioDashboard:/MicelioDashboard
      - /MicelioDashboard/node_modules
    environment:
      REACT_APP_API_BASE_URL: "http://localhost:3002/api/" # Para rodar localmente
      NODE_OPTIONS: "--openssl-legacy-provider"
    networks:
      - micelio_network
    restart: always

  backend:
    container_name: MicelioAPI
    image: node:lts-alpine
    working_dir: "/MicelioAPI"
    command: sh -c "yarn install && yarn dev"
    ports:
      - "3002:3002"     
    volumes:
      - ./MicelioAPI:/MicelioAPI
    environment: # Dados do banco de dados do backend deverão ser modificados aqui de acordo com o banco
      ENV: development
      HTTP_PORT: "3002"
      JWT_SECRET: ""
      DATABASE_HOST: "host.docker.internal" # Caso o mysql rode localmente na máquina e não na nuvem.
      DATABASE_PASSWORD: ""
      DATABASE_USER: ""
      DATABASE_CLIENT: "mysql"
      DATABASE: "micelio"
    networks:
      - micelio_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

networks:
  micelio_network:
    driver: bridge